import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/navbar/navbar";
import { AuthProvider } from '@/components/AuthProvider';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="h-screen flex flex-col">
        <AuthProvider>
        {/* Top navbar */}
        <div className="h-16">
          <Navbar/>
        </div>
        
        {/* Main layout: sidebar + main content */}
        <div className="flex flex-1 overflow-hidden">
          
          {/* Main content: takes rest of space, scrollable */}
          <main className="flex-1 overflow-y-auto p-4">
            {children}
          </main>
        </div>
        </AuthProvider>
      </body>
    </html>
  );
}
